name: Repository Creation Automation Workflow
on:
  workflow_dispatch:
    inputs:
      repository-name:
        description: 'Enter the name of the repository to create'
        required: true
      team-name:
        description: 'Enter the name of the team who owns the repository'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add any additional steps needed for the deployment process
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run Python script
        id: run-python-script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python main.py ${{ github.event.inputs.repository-name }} ${{ github.event.inputs.team-name }} ${{ secrets.GITHUB_TOKEN }}
          echo "::set-output name=summary::Deployment succeeded"
