name: Example Workflow
on:
  workflow_dispatch:
    inputs:
      repository-name:
        description: 'Enter the name of the repository to deploy to'
        required: true
      team-name:
        description: 'Enter the name of the team responsible for the deployment'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add any additional steps needed for the deployment process
      - name: Run Python script
        id: run-python-script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python deploy.py ${{ github.event.inputs.repository-name }} ${{ github.event.inputs.team-name }}
          echo "::set-output name=summary::Deployment succeeded"
      # Require approval before running the deployment
      - name: Request approval
        uses: peter-evans/request-changes@v1
        with:
          reviewers: ${{ github.event.inputs.team-name }}
          num-reviewers: 1
          changes-requested-message: Please approve this deployment.
      - name: Wait for approval
        uses: peter-evans/wait-for-approval@v2
        with:
          reviewers: ${{ github.event.inputs.team-name }}
          num-approvals: 1
          pull-request-message: Approved!
      - name: Run deployment
        run: |
          echo "Running deployment for ${{ github.event.inputs.repository-name }}..."
      # Use output of Python script as summary of the workflow
      - name: Set summary
        if: ${{ always() }}
        run: echo "Summary:: ${{ steps.run-python-script.outputs.summary }}"
